### ISSUE TITLE
cloud drift stretching site width on mobile

### ISSUE THREAD

**Issue by double-u-a** [double-u-a/vtpp#1]
Seems to be fine on desktop, maybe something to do with ```<meta viewport>```

**Comment by tomreeswilliams** [comment]
Is this still happening after 6520cd3? Can't see it on my phone any more.

Created a parent div to hide the overflow, rather than the main body of the site.

**Comment by double-u-a** [comment]
Ah brilliant, looks good on mobile!
Case "closed"
